#language: android
#language: node_js

#node_js:
#  - "6"

#android:
  #components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    #- build-tools-25.0.0

    # The SDK version used to compile your project
    #- android-25

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-17

sudo: true
os:
  - linux
dist:
  - xenial

before_install:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  #- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  #- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

  #- curl -o- -L https://yarnpkg.com/install.sh | bash

  - sudo apt-get update
  - sudo apt-get install -y build-essential nodejs openjdk-7-jdk
  - npm install --global yarn react-native-cli

  - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar -xvf android-sdk_r24.4.1-linux.tgz
  - cd android-sdk-linux
  - cp -R $TRAVIS_BUILD_DIR/android/licenses .
  - cd tools
  - ./android update sdk --no-ui
  - export PATH=${PATH}:$HOME/android-sdk-linux/platform-tools:$HOME/android-sdk-linux/tools:$HOME/android-sdk-linux/build-tools/22.0.1/

install:
  - yarn


script:
  - ls
  - ls $HOME
