#language: android
#language: node_js

#node_js:
#  - "6"

#android:
  #components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    #- build-tools-25.0.0

    # The SDK version used to compile your project
    #- android-25

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-17

sudo: true
os:
  - linux
dist:
  - xenial

before_install:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

  - sudo apt-get update
  - sudo apt-get install -y build-essential nodejs openjdk-7-jdk
  - npm install --global yarn react-native-cli

  - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar -xvf android-sdk_r24.4.1-linux.tgz
  #- cd android-sdk-linux
  #- cp -R $TRAVIS_BUILD_DIR/android/licenses .
  - cp -R $TRAVIS_BUILD_DIR/android/licenses android-sdk-linux/
  - set ANDROID_HOME=${PWD}/android-sdk-linux/
  #- cd tools
  #- ./android update sdk --no-ui --all --filter tools,platform-tools,build-tools-25.0.1,android-25,extra-android-m2repository,extra-android-support,extra-google-m2repository
  #- ./android update sdk --no-ui
  #- cd ../../
  - export PATH=${PATH}:$HOME/android-sdk-linux/platform-tools:$PWD/android-sdk-linux/tools:$PWD/android-sdk-linux/build-tools/22.0.1/

install:
  - yarn

script:
  - ls
  - ls $HOME
  - pwd

  #- keytool -genkey -v -noprompt -alias ${KEY_ALIAS} -dname "CN=MatheusDalMago, OU=ID, O=Private, L=Unknown, S=Unknown, C=BR" -keystore $TRAVIS_BUILD_DIR/android/app/${KEYSTORE_NAME} -keyalg RSA -keysize 2048 -validity 10000 -storepass ${KEYSTORE_PASSWORD} -keypass ${KEY_PASSWORD}
  - mkdir ~/.gradle/
  - echo "MYAPP_RELEASE_STORE_FILE=" > ~/.gradle/gradle.properties
  - echo ${KEYSTORE_NAME} >> ~/.gradle/gradle.properties
  - echo "\nMYAPP_RELEASE_KEY_ALIAS=" >> ~/.gradle/gradle.properties
  - echo ${KEY_ALIAS} >> ~/.gradle/gradle.properties
  - echo "\nMYAPP_RELEASE_STORE_PASSWORD=" >> ~/.gradle/gradle.properties
  - echo ${KEYSTORE_PASSWORD} >> ~/.gradle/gradle.properties
  - echo "\nMYAPP_RELEASE_KEY_PASSWORD=" >> ~/.gradle/gradle.properties
  - echo ${KEY_PASSWORD} >> ~/.gradle/gradle.properties

  - cat ~/.gradle/gradle.properties

  - cd $TRAVIS_BUILD_DIR/android/
  - ./gradlew assembleRelease
