os:
  - linux
dist:
  - xenial

sudo: true

before_install:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

  - sudo apt-get update
  - sudo apt-get install -y build-essential nodejs openjdk-7-jdk
  - npm install --global yarn react-native-cli

  - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar -xvf android-sdk_r24.4.1-linux.tgz

  - cp -R $TRAVIS_BUILD_DIR/android/licenses android-sdk-linux/
  - export ANDROID_HOME=${PWD}/android-sdk-linux/

  #- ./android update sdk --no-ui --all --filter tools,platform-tools,build-tools-25.0.1,android-25,extra-android-m2repository,extra-android-support,extra-google-m2repository

  - export PATH=${PATH}:$HOME/android-sdk-linux/platform-tools:$PWD/android-sdk-linux/tools:$PWD/android-sdk-linux/build-tools/22.0.1/

install:
  - yarn

script:
  #- keytool -genkey -v -noprompt -alias ${KEY_ALIAS} -dname "CN=MatheusDalMago, OU=ID, O=Private, L=Unknown, S=Unknown, C=BR" -keystore $TRAVIS_BUILD_DIR/android/app/${KEYSTORE_NAME} -keyalg RSA -keysize 2048 -validity 10000 -storepass ${KEYSTORE_PASSWORD} -keypass ${KEY_PASSWORD}
  - mkdir ~/.gradle/
  - echo MYAPP_RELEASE_STORE_FILE=${KEYSTORE_NAME} > ~/.gradle/gradle.properties
  - echo MYAPP_RELEASE_KEY_ALIAS=${KEY_ALIAS} >> ~/.gradle/gradle.properties
  - echo MYAPP_RELEASE_STORE_PASSWORD=${KEYSTORE_PASSWORD} >> ~/.gradle/gradle.properties
  - echo MYAPP_RELEASE_KEY_PASSWORD=${KEY_PASSWORD} >> ~/.gradle/gradle.properties

  - cd $TRAVIS_BUILD_DIR/android/
  - ./gradlew assembleRelease

  - ls app/build/outputs/apk/

notifications:
  email:
    on_success: change
    on_failure: change
